
package org.nsna.domain;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.nsna.serializers.JsonDateTimeDeserializer;
import org.nsna.serializers.JsonDateTimeSerializer;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * EduappProcessDetail generated by hbm2java
 */
@Entity
@Table(name = "EDUAPP_PROCESS_DETAIL", schema = "PUBLIC")
public class EduappProcessDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7474157472997475665L;

	private long eduappId;
	private Eduapplication eduapplication;
	private String reviewer;
	private String processingStatus;
	private Character returningStudent;
	private Character followupRequired;
	private BigDecimal reviewedMarkPercent;
	private Integer reviewedAnnualFamilyIncome;
	private Integer reviewedAnnualTutionFee;
	private Short reviewedApplCompletePercent;
	private Short reviewerPrefPercent;
	private String reviewerPrefComment;
	private Character exception;
	private Character reviewerReject;
	private Character reviewComplete;
	private String reviewerProcessingComment;	
	private Character rejected;	
	private BigDecimal markScore;
	private BigDecimal incomeScore;
	private BigDecimal hardshipScore;
	private BigDecimal appCompleteScore;
	private BigDecimal reviewerScore;
	private BigDecimal totalScore;

	private Short rank;
	private Integer awardAmount;
	private String checkNumber;
	private String fundName;	
	private Date crTs;
	private Date upTs;
	
	private String pBeneficiaryName;
	private String pBeneficiaryAddressLine1;
	private String pBeneficiaryAddressLine2;
	private String pBeneficiaryAddressLine3;
	private String pBeneficiaryAccountNumber;
	private String pBankName;
	private String pBankSwiftCode;
	private String pBranchIfscCode;
	private String pBranchAddressLine1;
	private String pBranchAddressLine2;
	private String pBranchAddressLine3;
	private Character useSwift;
	private Short reviewerPrefSB;
	private Short reviewerPrefSP;
	private Short reviewerPrefBL;
	private Short reviewerPrefAC;
	private Short reviewerPrefSS;
	private Short reviewerPrefGP;
	
	public EduappProcessDetail() {
	}

	public EduappProcessDetail(Eduapplication eduapplication) {
		this.eduapplication = eduapplication;
	}

	public EduappProcessDetail(Eduapplication eduapplication, String reviewer, String processingStatus,
			Character returningStudent, Character followupRequired, BigDecimal reviewedMarkPercent,
			Integer reviewedAnnualFamilyIncome, Integer reviewedAnnualTutionFee, Short reviewedApplCompletePercent,
			Short reviewerPrefPercent, String reviewerPrefComment, Character exception, Character reviewerReject,
			Character reviewComplete, String reviewerProcessingComment, Character rejected, BigDecimal markScore,
			BigDecimal incomeScore, BigDecimal hardshipScore, BigDecimal appCompleteScore, BigDecimal reviewerScore,
			BigDecimal totalScore, Short rank, Integer awardAmount, String checkNumber, String fundName, Date crTs,
			Date upTs, 	String pBeneficiaryName, String pBeneficiaryAddressLine1, String pBeneficiaryAddressLine2,
			String pBeneficiaryAddressLine3, String pBeneficiaryAccountNumber, String pBankName,
			String pBankSwiftCode, String pBranchIfscCode, String pBranchAddressLine1, String pBranchAddressLine2,
			String pBranchAddressLine3, Character useSwift, Short reviewerPrefSB, Short reviewerPrefSP, Short reviewerPrefBL,
			Short reviewerPrefAC, Short reviewerPrefSS, Short reviewerPrefGP) {
		this.eduapplication = eduapplication;
		this.reviewer = reviewer;
		this.processingStatus = processingStatus;
		this.returningStudent = returningStudent;
		this.followupRequired = followupRequired;
		this.reviewedMarkPercent = reviewedMarkPercent;
		this.reviewedAnnualFamilyIncome = reviewedAnnualFamilyIncome;
		this.reviewedAnnualTutionFee = reviewedAnnualTutionFee;
		this.reviewedApplCompletePercent = reviewedApplCompletePercent;
		this.reviewerPrefPercent = reviewerPrefPercent;
		this.reviewerPrefComment = reviewerPrefComment;
		this.exception = exception;
		this.reviewerReject = reviewerReject;
		this.reviewComplete = reviewComplete;
		this.reviewerProcessingComment = reviewerProcessingComment;
		this.rejected = rejected;
		this.markScore = markScore;
		this.incomeScore = incomeScore;
		this.hardshipScore = hardshipScore;
		this.appCompleteScore = appCompleteScore;
		this.reviewerScore = reviewerScore;
		this.totalScore = totalScore;
		this.rank = rank;
		this.awardAmount = awardAmount;
		this.checkNumber = checkNumber;
		this.fundName = fundName;
		this.crTs = crTs;
		this.upTs = upTs;
		this.pBeneficiaryName = pBeneficiaryName;
		this.pBeneficiaryAddressLine1 = pBeneficiaryAddressLine1;
		this.pBeneficiaryAddressLine2 = pBeneficiaryAddressLine2;
		this.pBeneficiaryAddressLine3 = pBeneficiaryAddressLine3;
		this.pBeneficiaryAccountNumber = pBeneficiaryAccountNumber;
		this.pBankName = pBankName;
		this.pBankSwiftCode = pBankSwiftCode;
		this.pBranchIfscCode = pBranchIfscCode;
		this.pBranchAddressLine1 = pBranchAddressLine1;
		this.pBranchAddressLine2 = pBranchAddressLine2;
		this.pBranchAddressLine3 = pBranchAddressLine3;
		this.useSwift = useSwift;
		this.reviewerPrefSB = reviewerPrefSB;
		this.reviewerPrefSP = reviewerPrefSP;
		this.reviewerPrefBL = reviewerPrefBL;
		this.reviewerPrefAC = reviewerPrefAC;
		this.reviewerPrefSS = reviewerPrefSS;
		this.reviewerPrefGP = reviewerPrefGP;
	}
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "eduapplication") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "EDUAPP_ID", unique = true, nullable = false)
	public long getEduappId() {
		return this.eduappId;
	}

	public void setEduappId(long eduappId) {
		this.eduappId = eduappId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@JsonBackReference
	public Eduapplication getEduapplication() {
		return this.eduapplication;
	}

	public void setEduapplication(Eduapplication eduapplication) {
		this.eduapplication = eduapplication;
	}

	@Column(name = "REVIEWER", length = 25)
	public String getReviewer() {
		return this.reviewer;
	}

	public void setReviewer(String reviewer) {
		if (reviewer != null && reviewer.equals("null")) {
			this.reviewer = null;
		} else {
			this.reviewer = reviewer;
		}
	}

	@Column(name = "PROCESSING_STATUS", length = 20)
	public String getProcessingStatus() {
		return this.processingStatus;
	}

	public void setProcessingStatus(String processingStatus) {
		this.processingStatus = processingStatus;
	}

	@Column(name = "RETURNING_STUDENT", length = 1)
	public Character getReturningStudent() {
		return this.returningStudent;
	}

	public void setReturningStudent(Character returningStudent) {
		this.returningStudent = returningStudent;
	}

	@Column(name = "FOLLOWUP_REQUIRED", length = 1)
	public Character getFollowupRequired() {
		return this.followupRequired;
	}

	public void setFollowupRequired(Character followupRequired) {
		this.followupRequired = followupRequired;
	}

	@Column(name = "REVIEWED_MARK_PERCENT", precision = 4, scale = 1)
	public BigDecimal getReviewedMarkPercent() {
		return this.reviewedMarkPercent;
	}

	public void setReviewedMarkPercent(BigDecimal reviewedMarkPercent) {
		this.reviewedMarkPercent = reviewedMarkPercent;
	}

	@Column(name = "REVIEWED_ANNUAL_FAMILY_INCOME")
	public Integer getReviewedAnnualFamilyIncome() {
		return this.reviewedAnnualFamilyIncome;
	}

	public void setReviewedAnnualFamilyIncome(Integer reviewedAnnualFamilyIncome) {
		this.reviewedAnnualFamilyIncome = reviewedAnnualFamilyIncome;
	}

	@Column(name = "REVIEWED_ANNUAL_TUTION_FEE")
	public Integer getReviewedAnnualTutionFee() {
		return this.reviewedAnnualTutionFee;
	}

	public void setReviewedAnnualTutionFee(Integer reviewedAnnualTutionFee) {
		this.reviewedAnnualTutionFee = reviewedAnnualTutionFee;
	}

	@Column(name = "REVIEWED_APPL_COMPLETE_PERCENT")
	public Short getReviewedApplCompletePercent() {
		return this.reviewedApplCompletePercent;
	}

	public void setReviewedApplCompletePercent(Short reviewedApplCompletePercent) {
		this.reviewedApplCompletePercent = reviewedApplCompletePercent;
	}

	@Column(name = "REVIEWER_PREF_PERCENT")
	public Short getReviewerPrefPercent() {
		return this.reviewerPrefPercent;
	}

	public void setReviewerPrefPercent(Short reviewerPrefPercent) {
		this.reviewerPrefPercent = reviewerPrefPercent;
	}

	@Column(name = "REVIEWER_PREF_COMMENT", length = 100)
	public String getReviewerPrefComment() {
		return this.reviewerPrefComment;
	}

	public void setReviewerPrefComment(String reviewerPrefComment) {
		this.reviewerPrefComment = reviewerPrefComment;
	}

	@Column(name = "EXCEPTION", length = 1)
	public Character getException() {
		return this.exception;
	}

	public void setException(Character exception) {
		this.exception = exception;
	}
	
	@Column(name = "REVIEWER_REJECT", length = 1)
	public Character getReviewerReject() {
		return this.reviewerReject;
	}

	public void setReviewerReject(Character reviewerReject) {
		this.reviewerReject = reviewerReject;
	}

	@Column(name = "REVIEW_COMPLETE", length = 1)
	public Character getReviewComplete() {
		return this.reviewComplete;
	}

	public void setReviewComplete(Character reviewComplete) {
		this.reviewComplete = reviewComplete;
	}

	@Column(name = "REVIEWER_PROCESSING_COMMENT", length = 1000)
	public String getReviewerProcessingComment() {
		return this.reviewerProcessingComment;
	}

	public void setReviewerProcessingComment(String reviewerProcessingComment) {
		this.reviewerProcessingComment = reviewerProcessingComment;
	}

	@Column(name = "REJECTED", length = 1)
	public Character getRejected() {
		return this.rejected;
	}

	public void setRejected(Character rejected) {
		this.rejected = rejected;
	}
	

	@Column(name = "MARK_SCORE", precision = 5, scale = 4)
	public BigDecimal getMarkScore() {
		return this.markScore;
	}

	public void setMarkScore(BigDecimal markScore) {
		this.markScore = markScore;
	}

	@Column(name = "INCOME_SCORE", precision = 5, scale = 4)
	public BigDecimal getIncomeScore() {
		return this.incomeScore;
	}

	public void setIncomeScore(BigDecimal incomeScore) {
		this.incomeScore = incomeScore;
	}

	@Column(name = "HARDSHIP_SCORE", precision = 5, scale = 4)
	public BigDecimal getHardshipScore() {
		return this.hardshipScore;
	}

	public void setHardshipScore(BigDecimal hardshipScore) {
		this.hardshipScore = hardshipScore;
	}

	@Column(name = "APP_COMPLETE_SCORE", precision = 5, scale = 4)
	public BigDecimal getAppCompleteScore() {
		return this.appCompleteScore;
	}

	public void setAppCompleteScore(BigDecimal appCompleteScore) {
		this.appCompleteScore = appCompleteScore;
	}

	@Column(name = "REVIEWER_SCORE", precision = 5, scale = 4)
	public BigDecimal getReviewerScore() {
		return this.reviewerScore;
	}

	public void setReviewerScore(BigDecimal reviewerScore) {
		this.reviewerScore = reviewerScore;
	}

	@Column(name = "TOTAL_SCORE", precision = 5, scale = 4)
	public BigDecimal getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(BigDecimal totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "RANK")
	public Short getRank() {
		return this.rank;
	}

	public void setRank(Short rank) {
		this.rank = rank;
	}

	@Column(name = "AWARD_AMOUNT")
	public Integer getAwardAmount() {
		return this.awardAmount;
	}

	public void setAwardAmount(Integer awardAmount) {
		this.awardAmount = awardAmount;
	}

	@Column(name = "CHECK_NUMBER", length = 20)
	public String getCheckNumber() {
		return this.checkNumber;
	}

	public void setCheckNumber(String checkNumber) {
		this.checkNumber = checkNumber;
	}

	@Column(name = "FUND_NAME", length = 100)
	public String getFundName() {
		return this.fundName;
	}

	public void setFundName(String fundName) {
		this.fundName = fundName;
	}	
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_TS", length = 23)
	@JsonSerialize(using=JsonDateTimeSerializer.class)
	public Date getCrTs() {
		return this.crTs;
	}

	@JsonDeserialize(using=JsonDateTimeDeserializer.class)
	public void setCrTs(Date crTs) {
		this.crTs = crTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UP_TS", length = 23)
	@JsonSerialize(using=JsonDateTimeSerializer.class)
	public Date getUpTs() {
		return this.upTs;
	}

	@JsonDeserialize(using=JsonDateTimeDeserializer.class)
	public void setUpTs(Date upTs) {
		this.upTs = upTs;
	}

	@Column(name = "P_BENEFICIARY_NAME", length = 35)	
	public String getpBeneficiaryName() {
		return pBeneficiaryName;
	}

	public void setpBeneficiaryName(String pBeneficiaryName) {
		this.pBeneficiaryName = pBeneficiaryName;
	}

	@Column(name = "P_BENEFICIARY_ADDRESS_LINE1", length = 35)	
	public String getpBeneficiaryAddressLine1() {
		return pBeneficiaryAddressLine1;
	}

	public void setpBeneficiaryAddressLine1(String pBeneficiaryAddressLine1) {
		this.pBeneficiaryAddressLine1 = pBeneficiaryAddressLine1;
	}

	@Column(name = "P_BENEFICIARY_ADDRESS_LINE2", length = 50)	
	public String getpBeneficiaryAddressLine2() {
		return pBeneficiaryAddressLine2;
	}


	public void setpBeneficiaryAddressLine2(String pBeneficiaryAddressLine2) {
		this.pBeneficiaryAddressLine2 = pBeneficiaryAddressLine2;
	}

	@Column(name = "P_BENEFICIARY_ADDRESS_LINE3", length = 35)		
	public String getpBeneficiaryAddressLine3() {
		return pBeneficiaryAddressLine3;
	}

	public void setpBeneficiaryAddressLine3(String pBeneficiaryAddressLine3) {
		this.pBeneficiaryAddressLine3 = pBeneficiaryAddressLine3;
	}

	@Column(name = "P_BENEFICIARY_ACCOUNT_NUMBER", length = 30)		
	public String getpBeneficiaryAccountNumber() {
		return pBeneficiaryAccountNumber;
	}

	public void setpBeneficiaryAccountNumber(String pBeneficiaryAccountNumber) {
		this.pBeneficiaryAccountNumber = pBeneficiaryAccountNumber;
	}

	@Column(name = "P_BANK_NAME", length = 35)	
	public String getpBankName() {
		return pBankName;
	}

	public void setpBankName(String pBankName) {
		this.pBankName = pBankName;
	}

	@Column(name = "P_BANK_SWIFT_CODE", length = 11)		
	public String getpBankSwiftCode() {
		return pBankSwiftCode;
	}

	public void setpBankSwiftCode(String pBankSwiftCode) {
		this.pBankSwiftCode = pBankSwiftCode;
	}

	@Column(name = "P_BRANCH_IFSC_CODE", length = 11)		
	public String getpBranchIfscCode() {
		return pBranchIfscCode;
	}

	public void setpBranchIfscCode(String pBranchIfscCode) {
		this.pBranchIfscCode = pBranchIfscCode;
	}

	@Column(name = "P_BRANCH_ADDRESS_LINE1", length = 35)		
	public String getpBranchAddressLine1() {
		return pBranchAddressLine1;
	}

	public void setpBranchAddressLine1(String pBranchAddressLine1) {
		this.pBranchAddressLine1 = pBranchAddressLine1;
	}

	@Column(name = "P_BRANCH_ADDRESS_LINE2", length = 35)		
	public String getpBranchAddressLine2() {
		return pBranchAddressLine2;
	}

	public void setpBranchAddressLine2(String pBranchAddressLine2) {
		this.pBranchAddressLine2 = pBranchAddressLine2;
	}

	@Column(name = "P_BRANCH_ADDRESS_LINE3", length = 35)		
	public String getpBranchAddressLine3() {
		return pBranchAddressLine3;
	}

	public void setpBranchAddressLine3(String pBranchAddressLine3) {
		this.pBranchAddressLine3 = pBranchAddressLine3;
	}

	@Column(name = "USE_SWIFT", length = 1)		
	public Character getUseSwift() {
		return useSwift;
	}

	public void setUseSwift(Character useSwift) {
		this.useSwift = useSwift;
	}
	
	@Column(name = "REVIEWER_PREF_SB")
	public Short getReviewerPrefSB() {
		return this.reviewerPrefSB;
	}

	public void setReviewerPrefSB(Short reviewerPrefSB) {
		this.reviewerPrefSB = reviewerPrefSB;
	}
	
	@Column(name = "REVIEWER_PREF_SP")
	public Short getReviewerPrefSP() {
		return this.reviewerPrefSP;
	}

	public void setReviewerPrefSP(Short reviewerPrefSP) {
		this.reviewerPrefSP = reviewerPrefSP;
	}
	
	@Column(name = "REVIEWER_PREF_BL")
	public Short getReviewerPrefBL() {
		return this.reviewerPrefBL;
	}

	public void setReviewerPrefBL(Short reviewerPrefBL) {
		this.reviewerPrefBL = reviewerPrefBL;
	}
	
	@Column(name = "REVIEWER_PREF_AC")
	public Short getReviewerPrefAC() {
		return this.reviewerPrefAC;
	}

	public void setReviewerPrefAC(Short reviewerPrefAC) {
		this.reviewerPrefAC = reviewerPrefAC;
	}
	
	@Column(name = "REVIEWER_PREF_SS")
	public Short getReviewerPrefSS() {
		return this.reviewerPrefSS;
	}

	public void setReviewerPrefSS(Short reviewerPrefSS) {
		this.reviewerPrefSS = reviewerPrefSS;
	}
	
	@Column(name = "REVIEWER_PREF_GP")
	public Short getReviewerPrefGP() {
		return this.reviewerPrefGP;
	}

	public void setReviewerPrefGP(Short reviewerPrefGP) {
		this.reviewerPrefGP = reviewerPrefGP;
	}
	
	@PrePersist
	void createdAt() {
		this.crTs = new Date();
		this.upTs = new Date();
	}
	
	@PreUpdate
	void statusAndUpdatedAt() {
		this.upTs = new Date();

		if (this.rejected != null && this.rejected.equals('Y') && !this.processingStatus.equals("Rejected")) {
			this.setProcessingStatus("Rejected");
		} else if (this.checkNumber != null && !this.checkNumber.isEmpty()) {
			this.setProcessingStatus("Awarded");
		} else if (this.awardAmount != null && this.awardAmount > 0) {
			this.setProcessingStatus("Approved");
		} else if (this.reviewerReject != null && this.reviewerReject.equals('Y') && 
					this.reviewComplete != null && this.reviewComplete.equals('Y')) {
			this.setProcessingStatus("RecommendReject");			
		} else if (this.reviewComplete != null && this.reviewComplete.equals('Y')){
			this.setProcessingStatus("ReviewComplete");
		} else if (this.reviewer != null){
			this.setProcessingStatus("Assigned");
		} else {
			this.setProcessingStatus("New");
		}
	}
	
}
