package org.nsna.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.FetchMode;
import org.hibernate.annotations.Fetch;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * EduappAttachment generated by hbm2java
 */
//@JsonIgnoreProperties({"eduappAttachmentData"})
@Entity
@Table(name = "EDUAPP_ATTACHMENT", schema = "PUBLIC")
public class EduappAttachment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4858957989472887672L;
	private Long id;
	private Eduapplication eduapplication;
	private Integer documentOrder;
	private String documentCategory;
	private String documentOriginalFilename;
	private EduappAttachmentData eduappAttachmentData;

	public EduappAttachment() {
	}

	public EduappAttachment(Eduapplication eduapplication) {
		this.eduapplication = eduapplication;
	}

	public EduappAttachment(Eduapplication eduapplication, Integer documentOrder, String documentCategory,
			String documentOriginalFilename, EduappAttachmentData eduappAttachmentData) {
		this.eduapplication = eduapplication;
		this.documentOrder = documentOrder;
		this.documentCategory = documentCategory;
		this.documentOriginalFilename = documentOriginalFilename;
		this.eduappAttachmentData = eduappAttachmentData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EDUAPP_ID", nullable = false)
	@JsonBackReference
	public Eduapplication getEduapplication() {
		return this.eduapplication;
	}

	public void setEduapplication(Eduapplication eduapplication) {
		this.eduapplication = eduapplication;
	}

	@Column(name = "DOCUMENT_ORDER")
	public Integer getDocumentOrder() {
		return this.documentOrder;
	}

	public void setDocumentOrder(Integer documentOrder) {
		this.documentOrder = documentOrder;
	}

	@Column(name = "DOCUMENT_CATEGORY", length = 20)
	public String getDocumentCategory() {
		return this.documentCategory;
	}

	public void setDocumentCategory(String documentCategory) {
		this.documentCategory = documentCategory;
	}

	@Column(name = "DOCUMENT_ORIGINAL_FILENAME", length = 50)
	public String getDocumentOriginalFilename() {
		return this.documentOriginalFilename;
	}

	public void setDocumentOriginalFilename(String documentOriginalFilename) {
		this.documentOriginalFilename = documentOriginalFilename;
	}

	
	//@OneToOne(fetch = FetchType.LAZY, mappedBy = "eduappAttachment", cascade = CascadeType.ALL)
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn (name = "EDU_ATTACHMENT_ID", insertable = false, updatable = false)
	@Transient
	@JsonManagedReference
	@JsonIgnore
	public EduappAttachmentData getEduappAttachmentData() {
		return this.eduappAttachmentData;
	}

	public void setEduappAttachmentData(EduappAttachmentData eduappAttachmentData) {
		this.eduappAttachmentData = eduappAttachmentData;
	}

}
