package org.nsna.domain;

import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * EduappAttachmentData generated by hbm2java
 */
@JsonIgnoreProperties({"document"})
@Entity
@Table(name = "EDUAPP_ATTACHMENT_DATA", schema = "PUBLIC")
public class EduappAttachmentData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6892160952694308188L;
	private long eduappAttachmentId;
	private EduappAttachment eduappAttachment;
	private Blob document;

	public EduappAttachmentData() {
	}

	public EduappAttachmentData(EduappAttachment eduappAttachment) {
		this.eduappAttachment = eduappAttachment;
	}

	public EduappAttachmentData(EduappAttachment eduappAttachment, Blob document) {
		this.eduappAttachment = eduappAttachment;
		this.document = document;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "eduappAttachment") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "EDUAPP_ATTACHMENT_ID", unique = true, nullable = false)
	public long getEduappAttachmentId() {
		return this.eduappAttachmentId;
	}

	public void setEduappAttachmentId(long eduappAttachmentId) {
		this.eduappAttachmentId = eduappAttachmentId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@JsonBackReference
	public EduappAttachment getEduappAttachment() {
		return this.eduappAttachment;
	}

	public void setEduappAttachment(EduappAttachment eduappAttachment) {
		this.eduappAttachment = eduappAttachment;
	}

	@Column(name = "DOCUMENT")
	public Blob getDocument() {
		return this.document;
	}

	public void setDocument(Blob document) {
		this.document = document;
	}

}
