package org.nsna.domain;
// Generated Jul 6, 2016 7:50:03 PM by Hibernate Tools 4.3.1.Final

import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.nsna.serializers.JsonDateDeserializer;
import org.nsna.serializers.JsonDateSerializer;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * EduappConfig generated by hbm2java
 */
@Entity
@Table(name = "EDUAPP_CONFIG", schema = "PUBLIC")
public class EduappConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6014950370275515254L;
	private Long id;
	private String appYear;
	private Date appWindowStartDate;
	private Date appWindowEndDate;
	private String environmentText;
	private String passcodeHash;
	private Integer defaultAwardAmount;
	private String region;
	private String scholarshipAwardNotificationDate;

	public EduappConfig() {
	}

	public EduappConfig(String appYear, Date appWindowStartDate, Date appWindowEndDate, 
			String environmentText, String passcodeHash, int defaultAwardAmount,
			String region, String scholarshipAwardNotificationDate) {
		
		this.appYear = appYear;
		this.appWindowStartDate = appWindowStartDate;
		this.appWindowEndDate = appWindowEndDate;
		this.environmentText = environmentText;
		this.passcodeHash = passcodeHash;
		this.defaultAwardAmount = defaultAwardAmount;
		this.region = region;
		this.scholarshipAwardNotificationDate = scholarshipAwardNotificationDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "APP_YEAR", length = 4)
	public String getAppYear() {
		return this.appYear;
	}

	public void setAppYear(String appYear) {
		this.appYear = appYear;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_WINDOW_START_DATE", length = 8)
	@JsonSerialize(using=JsonDateSerializer.class)	
	public Date getAppWindowStartDate() {
		return this.appWindowStartDate;
	}

	@JsonDeserialize(using=JsonDateDeserializer.class)
	public void setAppWindowStartDate(Date appWindowStartDate) {
		this.appWindowStartDate = appWindowStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_WINDOW_END_DATE", length = 8)
	@JsonSerialize(using=JsonDateSerializer.class)	
	public Date getAppWindowEndDate() {
		return this.appWindowEndDate;
	}

	@JsonDeserialize(using=JsonDateDeserializer.class)	
	public void setAppWindowEndDate(Date appWindowEndDate) {
		this.appWindowEndDate = appWindowEndDate;
	}
	
	
	@Column(name = "ENVIRONMENT_TEXT", length = 80)
	public String getEnvironmentText() {
		return this.environmentText;
	}

	public void setEnvironmentText(String environmentText) {
		this.environmentText = environmentText;
	}
	
	@Column(name = "PASSCODE_HASH", length = 100)	
	public String getPasscodeHash() {
		return passcodeHash;
	}

	public void setPasscodeHash(String passcodeHash) {
		this.passcodeHash = passcodeHash;
	}

	@Column(name = "DEFAULT_AWARD_AMOUNT")	
	public Integer getDefaultAwardAmount() {
		return defaultAwardAmount;
	}

	public void setDefaultAwardAmount(Integer defaultAwardAmount) {
		this.defaultAwardAmount = defaultAwardAmount;
	}

	@Column(name = "REGION", length = 10)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}
	
	@Column(name = "SCHLRSP_AWARD_NOTIF_DATE", length = 10)
	public String getScholarshipAwardNotificationDate() {
		return this.scholarshipAwardNotificationDate;
	}

	public void setScholarshipAwardNotificationDate(String scholarshipAwardNotificationDate) {
		this.scholarshipAwardNotificationDate = scholarshipAwardNotificationDate;
	}
	
	@Transient
	  public boolean getEduappWindow() {
		 if ((new Date()).compareTo(this.getAppWindowStartDate()) >=0 &&  
				 	(new Date()).compareTo(this.getAppWindowEndDate()) <=0) {
			 return true;
		 } else {
			 return false;
		 }
	  }	  
	  
	  @Transient
	  public String getEduappWindowStart() {
		  Format monthFormatter = new SimpleDateFormat("MMMM"); 
			 Format dayFormatter = new SimpleDateFormat("dd");
			 String windowStart;
			 windowStart =  monthFormatter.format(this.getAppWindowStartDate()) + "/"
					 	+ dayFormatter.format(this.getAppWindowStartDate()) ;
			 return windowStart;
	  }	 
	  
	  @Transient
	  public int getAcademicEndYear() {
		  Integer i = Integer.parseInt(this.appYear);
		  return i+1;
				  
	  }	  
	  
	  @Transient
	  public String getEduappWindowEnd() {
		  Format monthFormatter = new SimpleDateFormat("MMMM"); 
			 Format dayFormatter = new SimpleDateFormat("dd");
			 String windowEnd;
			 windowEnd =  monthFormatter.format(this.getAppWindowEndDate()) + "/"
					 	+ dayFormatter.format(this.getAppWindowEndDate()) ;
			 return windowEnd;
	  }		  
	  
	  @Transient
	  public String getAppWindowClosedMessage() {
		 Format monthFormatter = new SimpleDateFormat("MMMM"); 
		 Format dayFormatter = new SimpleDateFormat("dd");
		 String msg;
		 msg = "Application window is currently closed. " +
				 	"The education scholarship applications are accepted from "
				 	+ monthFormatter.format(this.getAppWindowStartDate()) + " / "
				 	+ dayFormatter.format(this.getAppWindowStartDate()) + " to "
				 	+ monthFormatter.format(this.getAppWindowEndDate()) + " / "
					+ dayFormatter.format(this.getAppWindowEndDate()) + ".";
		 return msg;
	  }	  
	  
	  
	  public void setEduappWindow(boolean eduappWindow) {
	  }	

}
